# Generated by Django 6.0.3 on 2026-03-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itinerary",
            options={"ordering": ["-created_at"]},
        ),
    ]
