# Generated by Django 5.2.12 on 2026-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0003_itinerary_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="activities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
