# Generated by Django 5.2.12 on 2026-03-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0004_itinerary_activities_itinerary_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
