# Generated by Django 5.2.12 on 2026-03-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itineraries", "0005_itinerary_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("booked", "Booked"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="planning",
                help_text="Status of the itinerary (only visible to owner)",
                max_length=20,
            ),
        ),
    ]
