# Generated by Django 5.2.12 on 2026-03-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0006_add_status_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="planning",
                help_text="Status of the itinerary (only visible to owner)",
                max_length=20,
            ),
        ),
    ]
