# Generated by Django 5.2.12 on 2026-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
