repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: ["--exclude=venv,migrations"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: django-system-check
        name: Django system check
        entry: .venv/bin/python manage.py check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: django-migrations-check
        name: Django migrations check
        entry: .venv/bin/python manage.py makemigrations --check --dry-run --no-input
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: django-tests
        name: Django tests
        entry: .venv/bin/python manage.py test --verbosity=1
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
